### ISSUE TITLE
数组类型的数据如何处理?

### ISSUE THREAD

**Issue by LiHaoGit** [alibaba/nopage#19]
例如我的数据是
```
{
 list:[1,2,3]
}
```
目前我的做法是自己写一个`ListComponent`来实现  
`noform` 对于这种类型的数据如何处理呢？  
可否用`repeater`

**Comment by quirkyshop** [comment]
repeater是Array<Object> .如果你的场景是纯数字的话可以自己实现。

但建议用repeater，在提交或者获取时格式化一下，只是一个map的成本。先关了，任何关于repe'ter的问题欢迎你提issue😬

**Comment by quirkyshop** [comment]
Array< T >
