### ISSUE TITLE
core/form scrollToError not work

### ISSUE THREAD

**Issue by gogoyqj** [alibaba/nopage#20]
**Describe the bug**
手动调用 `form.core.scrollToError()`，并不能滚动到错误元素

**Additional context**
component/FormItem.js 有 id 属性的元素，使用的 FormItem id
core/form.js scrollToError 定位元素使用的 id，是 core/item id

两个 id 不一致【某些条件下】，故无法定位，尝试在 component/FormItem.js render 内给任一元素添加 `id={itemContext.item.id}` 即可修复

![image](https://user-images.githubusercontent.com/1776278/50332076-fc8fc280-053b-11e9-84b7-bdb7a85ca413.png)

**Comment by quirkyshop** [comment]
@gogoyqj 抱歉这么久才回复这个issue，在排查过程中没有复现，应该是种没有覆盖的情况，但是也按照这种修复去改了 noform@1.1.47

一般来说两个id不应该不一致，如果复现欢迎你再open这个case，其实你察觉到了这个问题，也知道修改的方式，也欢迎你加入我们贡献些代码，PR是最好的支持形式，谢啦
