### ISSUE TITLE
Repeater组件的每一行能否增加自定义按钮功能？自定义按钮支持条件显示？

### ISSUE THREAD

**Issue by Sally-Xiao** [alibaba/nopage#22]
![image](https://user-images.githubusercontent.com/15962046/50631748-797d5c00-0f80-11e9-8169-185d72ae5cca.png)
如上图所示，用户输入完条形码之后，系统需要给一个打印条形码的功能，我希望能跟保存，删除按钮放在一起。

另外，自定义按钮能否支持条件显示，比如当每一行的数据处于预览态时，打印按钮出现，其他状态按钮隐藏

**Comment by quirkyshop** [comment]
@Sally-Xiao 
https://alibaba.github.io/nopage/#/nopage/noform/oper-btn 在noform@1.1.46 中已经增强了这个功能
Repeater增加这个属性方法 **renderOper**
