### ISSUE TITLE
子组件未渲染完成时，不能获取formItem的name值

### ISSUE THREAD

**Issue by buyou0821** [alibaba/nopage#23]
#### 描述
我在子组件(结构大概是`<antd.Modal visible={false}><Form /><antd.Modal>`)的`componentWillMount`里创建了`FormCore`，然后调用了父组件的方法把这个`FormCore`的引用传给了父组件，用以在父组件中操作form

#### 需求
需要在父组件中获取子组件中所有FormItem的name值，用以根据业务判断是否需要赋值一个初始化的值

#### 问题
因为`FormCore.getValues()`是不能获取到空值的属性的，所以我改为通过遍历`FormCore.children`的方式获取name，我在父组件首次设置子组件的antd.Modal的visible为true，并获取core.children时，因为渲染没有完成导致core.children里是空的, 所以我还是没有办法获取表单里的name

现在是通过设置`antd.Modal`的`forceRender`来解决，但是之前用`antd`的`form.getFieldsValue()`可以获得没有值的name，比如：{key: null}，就不用forceRender了

#### 期望
希望有一个比如`formCore.getNames()`的方式来获取formItem的name

**Comment by quirkyshop** [comment]
NoForm是基于渲染子组件的didMount来上报子元素的name的，所以无法在渲染前获取所有子元素。有以下两个办法可以解决(其实作用都一样）

1. initialized
```
new FormCore({
    initialized: () => {
        formCore.children.map(item => item.name).filter(name => !name.startsWith('__'))
   }
});
```

2. 在didMount里能获取
```jsx
formCore.children.map(item => item.name).filter(name => !name.startsWith('__'))
```

**Comment by quirkyshop** [comment]
备注：之所以需要过滤 __ 是因为NoForm 把无名FormItem 及 If 也赋予了随机name，因此需要过滤掉
