### ISSUE TITLE
可否添加错误信息？

### ISSUE THREAD

**Issue by buyou0821** [alibaba/nopage#24]
**描述**
在antd中，我对DatePicker传入的值不是moment对象的时候，noForm没有显示值也没有报错

**期望**
希望报出antd的错误提示
![default](https://user-images.githubusercontent.com/37977488/53159842-a43f7480-3601-11e9-90f2-6dca21fb5d9d.png)

**Comment by quirkyshop** [comment]
感谢反馈。
NoWrapper 只是透传value，没有包装错误提示，刚刚试了一下，antd或NoWrapper包裹后的antd也没复现这种情况，贴上复现代码可以更快速定位下。

可以访问 https://quirkyshop.github.io/noform-start-app/#/， 然后控制台输入
```jsx
window.antdCore.setItemValue('DatePicker', '2019-05-20');
```
就可以看到页面崩溃并报出错误提醒了，先close了，复现再打开
